DROP TABLE BVG_COFFEE;

CREATE TABLE BVG_COFFEE (
    CID NUMBER,
    CNAME VARCHAR2(50) NOT NULL, 
    CCOLOR VARCHAR2(25),
    CFLAVOR VARCHAR2(25),
    CORIGIN VARCHAR2(25),
    CONSTRAINT BVG_PRIMARY_KEY PRIMARY KEY (CID));

CREATE SEQUENCE coffee_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'DALGONA', 'BEIGE', 'CHOCOLATE', 'INDIA');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'MOCHA', 'BROWN', 'OREO', 'ETHIOPIA');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'CAPUCCINO', 'WHITE', 'VANILLA', 'ITALY');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'ESPRESSO', 'DARK BROWN', 'HAZELNUT', 'USA');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'LATTE', 'CREAM', 'CARAMEL', 'FRANCE');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'AMERICANO', 'BLACK', 'PLAIN', 'BRAZIL');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'IRISH COFFEE', 'DARK', 'WHISKEY', 'IRELAND');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'COLD BREW', 'CLEAR', 'COCOA', 'COLOMBIA');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'VIETNAMESE COFFEE', 'BROWN', 'CONDENSED MILK', 'VIETNAM');
INSERT INTO BVG_COFFEE VALUES (coffee_seq.NEXTVAL, 'AFFOGATO', 'GOLDEN', 'COFFEE ICE CREAM', 'ITALY');

COMMIT;